throwErrorOnExtraParameters: true

templates:
  plain: !template
    mapExport: true
    attributes:
      map: !map
        maxWidth: 1000
        maxHeight: 1000
        maxDpi: 400
        zoomSnapTolerance: 0.025
        zoomLevelSnapStrategy: CLOSEST_LOWER_SCALE_ON_TIE
        zoomLevels: !zoomLevels
          scales: [250, 500, 1000, 2500, 5000, 10000, 25000, 50000, 100000]
    processors:
      - !createMap {}
